### ISSUE TITLE
Refactor before Phase 1 Submission

### ISSUE THREAD

**Issue by mtoohey31** [tli-group-4-grimm/backend#34]
- [x] Attributes: @Mogtaba-Alim
- [x] Constants: @Mogtaba-Alim
- [x] Entities: @gnguralnick, PR  #36
- [x] Entitybuilder: @Mogtaba-Alim PR #58 
- [x] Entitypackagers: @ianlavine
- [x] Entityparsers: @ianlavine PR #58 
- [x] Server: @mtoohey31, #45
- [x] Routes: @mtoohey31, PR #35
- [x] Fetchers: @mtoohey31, PR #51
---

Sorry for the pings everyone, just putting this here like this so we can keep track of the pull requests for each refactor in a GitHub issue.
